name: three_dart_jsm
description: three.js example/jsm rewrite by Dart. for three_dart Dart 3D library. an easy to use, lightweight, cross-platform, general purpose 3D library. 
version: 0.0.10
homepage: https://github.com/wasabia/three_dart_jsm
publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_dart:
    git:
      url: git@github.com:onecalfman/three_dart.git
      ref: HEAD
  flutter_gl:
    git:
      url: git@github.com:onecalfman/flutter_gl.git
      ref: HEAD
      path: flutter_gl
  typr_dart: ^0.0.2
  opentype_dart: ^0.0.1
  universal_html: ^2.0.8
  image: ^4.1.7
  archive: ^4.0.7
  
path: ../../three_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

